# Generated by Django 2.1.7 on 2019-03-25 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BdnkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=20)),
                ('imei', models.CharField(default='', max_length=20)),
                ('lat', models.CharField(default='', max_length=20)),
                ('long', models.CharField(default='', max_length=20)),
                ('altitude', models.CharField(default='', max_length=20)),
                ('locate_mode', models.CharField(default='', max_length=20)),
                ('bat', models.CharField(default='', max_length=20)),
                ('si', models.CharField(default='', max_length=20)),
                ('elapse', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BdnkDeviceIdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=20)),
                ('imei', models.CharField(default='', max_length=20)),
                ('ccid', models.CharField(default='', max_length=30)),
                ('imsi', models.CharField(default='', max_length=20)),
                ('version', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='Z001', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BdnkDeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=20)),
                ('imei', models.CharField(default='', max_length=20)),
                ('interval', models.CharField(default='', max_length=20)),
                ('led', models.CharField(default='', max_length=20)),
                ('enable_shut_off_by_pwrkey', models.CharField(default='', max_length=20)),
                ('run_status', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='13800000000', max_length=64)),
                ('bdnk_device_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Topic'),
        ),
    ]
