# Generated by Django 2.1.7 on 2019-03-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190325_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdnkdevicestatus',
            name='bdnk_device_status',
        ),
    ]
