# Generated by Django 2.1.7 on 2019-02-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='dateadded',
            new_name='date_added',
        ),
    ]
