# Generated by Django 2.1.7 on 2019-03-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190323_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdnkdata',
            name='bdnk_device_data_record',
        ),
    ]
